blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('list/', BlogListView.as_view(), name='blog_post_list'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('update/<slug:slug>/', BlogUpdateView.as_view(), name='update'),

]

client/urls.py
from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientsDetailView
from django.urls import path

app_name = ClientConfig.name
urlpatterns = [
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', ClientsDetailView.as_view(), name='client_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('client/', include('client.urls', namespace='client'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import Home, MailingTryListView, MailingListView, \
    MailingCreateView, MailingDeleteView, MailingUpdateView

app_name = MailingConfig.name
urlpatterns = [
    path('', cache_page(1)(Home.as_view()), name='index'),
    path('mailing_report/', MailingTryListView.as_view(),
         name='mailing_report'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(),
         name='mailing_delete'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(),
         name='mailing_update'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, activate_account, ActivationOk, ActivationFailed, gen_pass, \
    UserForgotPasswordView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('verify/<str:uidb64>/', activate_account, name='email_verification'),
    path('success', ActivationOk.as_view(), name='activation_ok'),
    path('failed', ActivationFailed.as_view(), name='activation_failed'),
    path("gen_pass/", gen_pass, name="gen_pass"),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

mailing/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, DateTimeInput
from client.models import MailingClient
from mailing.models import Mail, MailingSettings
from django import forms


class MailForm(ModelForm):
    clients = MailingClient.objects.all()
    client_to_message = ModelMultipleChoiceField(queryset=clients,
                                                 required=False)

    class Meta:
        model = Mail
        fields = (
        'mailing_subject', 'mailing_body', 'client_to_message', 'all_clients',)


class SettingsForm(ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('mailing_time_start', 'mailing_time_end', 'mailing_periods',)
        widgets = {
            'mailing_time_start': DateTimeInput(
                attrs={'type': 'datetime-local'}),
            'mailing_time_end': DateTimeInput(attrs={'type': 'datetime-local'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        instance = kwargs.get('instance')

        if instance:

            mailing_time_start = instance.mailing_time_start
            mailing_time_end = instance.mailing_time_end

            if mailing_time_start:
                self.fields['mailing_time_start'].widget = forms.TextInput(
                    attrs={
                        'value': mailing_time_start.strftime('%Y-%m-%dT%H:%M')})
            if mailing_time_end:
                self.fields['mailing_time_end'].widget = forms.TextInput(
                    attrs={
                        'value': mailing_time_end.strftime('%Y-%m-%dT%H:%M')})

mailing/views.py
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, DeleteView, ListView, \
    UpdateView
from blog.models import BlogPost
from client.models import MailingClient
from config import settings
from mailing.forms import SettingsForm, MailForm
from mailing.models import Mail, MailingSettings, MailingTry


class Home(TemplateView):

    template_name = "mailing/index.html"

    def get_context_data(self, **kwargs):

        context = {}
        mails = Mail.objects.all().count()
        active = MailingSettings.objects.filter(
            mailing_status='AC').values_list().count(),
        clients = MailingClient.objects.all().count()
        random_article = BlogPost.objects.order_by('?')[:3]
        context['mails'] = mails
        context['active'] = active[0]
        context['clients'] = clients
        context['random_article'] = random_article
        return context


class MailingCreateView(LoginRequiredMixin, CreateView):

    template_name = "mailing/mail_form.html"
    model = MailingSettings
    form_class = SettingsForm
    success_url = reverse_lazy('mailing:mailing_list')
    mail_data = ''
    mail_status = 'OK'

    def get_context_data(self, **kwargs):

        context_data = super().get_context_data(**kwargs)
        MailFormset = inlineformset_factory(MailingSettings, Mail,
                                            form=MailForm, can_delete=False,
                                            extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = MailFormset(self.request.POST or None,
                                                  instance=self.object)
        else:
            context_data['formset'] = MailFormset(instance=self.object)

        return context_data

    def form_valid(self, form):

        data = self.get_context_data()
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        formset = data['formset']
        client_email = []
        mailing_subject = ''
        mailing_body = ''
        for fo in formset:
            if fo.is_valid():
                clients = fo.cleaned_data.get('client_to_message').values_list()
                for i in clients:
                    client_email.append(i[2])
                mailing_subject = fo.cleaned_data.get('mailing_subject')
                mailing_body = fo.cleaned_data.get('mailing_body')
                all_clients = fo.cleaned_data.get('all_clients')
                if all_clients:
                    client_email = list(
                        MailingClient.objects.all().values_list('contact_email',
                                                                flat=True))
        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.mailing_status = "AC"
            mailing.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.author = self.request.user
            formset.save()
        self.object.save()
        ct = datetime.now()

        try:
            if self.object.mailing_time_start.timestamp() <= ct.timestamp() <= self.object.mailing_time_end.timestamp():
                sending = send_mail(mailing_subject, mailing_body,
                                    settings.DEFAULT_FROM_EMAIL,
                                    recipient_list=client_email,
                                    fail_silently=False)
                if sending == 1:
                    self.mail_status = 'OK'
                else:
                    self.mail_status = 'Не отправлено'

            if (self.object.mailing_periods == "DL") and ((
                                                                  self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(
                days=1)):
                self.object.mailing_status = 'FI'
                self.object.save()
            elif (self.object.mailing_periods == "WL") and ((
                                                                    self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(
                days=6)):
                self.object.mailing_status = 'FI'
                self.object.save()
            elif (self.object.mailing_periods == "ML") and ((
                                                                    self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(
                days=30)):
                self.object.mailing_status = 'FI'
                self.object.save()

            MailingTry.objects.create(mailing=self.object,
                                      mailing_try=datetime.now(),
                                      mailing_try_status=self.object.mailing_status,
                                      mailing_response=self.mail_status)
            return super().form_valid(form)
        except AttributeError:
            form.add_error(None, 'Установите дату рассылки.')
            return super(MailingCreateView, self).form_invalid(form)


class MailingListView(LoginRequiredMixin, ListView):

    template_name = "mailing/mailing_list.html"
    model = Mail
    paginate_by = 10
    extra_context = {
        'title': 'Мои рассылки'
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.author != self.request.user and not self.request.user.status_type == 'MANAGER':
            raise PermissionDenied
        return self.object

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class MailingDeleteView(LoginRequiredMixin, DeleteView):

    model = Mail
    template_name = "mailing/mailing_delete.html"
    success_url = reverse_lazy('mailing:mailing_list')

    def delete(self, request, *args, **kwargs):

        self.object = self.get_object()

        self.object.delete()
        messages.success(request, 'Рассылка успешно удалена.')
        return redirect(self.success_url)


class MailingUpdateView(LoginRequiredMixin, UpdateView):

    template_name = "mailing/mail_form_update.html"
    model = MailingSettings
    form_class = SettingsForm
    success_url = reverse_lazy('mailing:mailing_list')
    mail_data = ''
    mail_status = 'OK'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.author != self.request.user:
            raise PermissionDenied
        return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MailFormset = inlineformset_factory(MailingSettings, Mail,
                                            form=MailForm, can_delete=False,
                                            extra=0, edit_only=True)
        if self.request.method == 'POST':
            context_data['formset'] = MailFormset(self.request.POST or None,
                                                  instance=self.object)
        else:
            context_data['formset'] = MailFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        data = self.get_context_data()
        self.object = form.save()
        formset = data['formset']
        client_email = []
        mailing_subject = ''
        mailing_body = ''
        for fo in formset:
            if fo.is_valid():
                clients = fo.cleaned_data.get('client_to_message').values_list()
                for i in clients:
                    client_email.append(i[2])
                mailing_subject = fo.cleaned_data.get('mailing_subject')
                mailing_body = fo.cleaned_data.get('mailing_body')
                all_clients = fo.cleaned_data.get('all_clients')
                if all_clients:
                    client_email = list(
                        MailingClient.objects.all().values_list('contact_email',
                                                                flat=True))
        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.mailing_status = "AC"
            mailing.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        self.object.save()
        ct = datetime.now()

        try:
            if self.object.mailing_time_start.timestamp() <= ct.timestamp() <= self.object.mailing_time_end.timestamp():
                sending = send_mail(mailing_subject, mailing_body,
                                    settings.DEFAULT_FROM_EMAIL,
                                    recipient_list=[client_email],
                                    fail_silently=False)
                if sending == 1:
                    self.mail_status = 'OK'
                else:
                    self.mail_status = 'Не отправлено'

            if (self.object.mailing_periods == "DL") and ((
                                                                  self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(
                days=1)):
                self.object.mailing_status = 'FI'
                self.object.save()
            elif (self.object.mailing_periods == "WL") and ((
                                                                    self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(
                days=6)):
                self.object.mailing_status = 'FI'
                self.object.save()
            elif (self.object.mailing_periods == "ML") and ((
                                                                    self.object.mailing_time_end - self.object.mailing_time_start) <= timedelta(

mailing/templates/mailing/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылок send_mail</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <style>
        html, body, .container-fluid, .row, .col-md-3 {
            height: 100%;
        }

        {
        %
        static
        'bootstrap/css/bootstrap.min.css'
        %
        }
        .title {
            margin-top: 50px;
        }
    </style>
</head>
<body>

<div class="container-fluid h-100">
    <div class="row h-100">
        <div class="col-md-3">
            <h1 class="visually-hidden">Меню управления</h1>
            <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark h-100" style="width: 280px;">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-black text-decoration-none">
                    <svg class="bi pe-none me-2" width="40" height="50">
                        <use xlink:href=""></use>
                    </svg>
                    Меню управления
                </a>
                <hr>
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a href="{% url 'mailing:index' %}" class="nav-link text-black" aria-current="page">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="#home"></use>
                            </svg>
                            Главная страница
                        </a>
                    </li>
                    <div class="container">
                        <a href="{% url 'blog:blog_post_list' %}" class="nav-link text-black" >
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'blog:blog_post_list' %}"></use>
                            </svg>
                            Блог
                        </a>
                    </div>
                    <li>
                        {% if user.is_authenticated %}
                        <div class="container">
                            <a href="{% url 'mailing:mailing_list' %}" class="nav-link text-black">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="{% url 'mailing:mailing_list' %}"></use>
                                </svg>
                                Рассылки
                            </a>
                        </div>
                        {% endif %}

                    </li>


                    <li>

                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <div class="container">
                            <a href="{% url 'client:client_list' %}" class="nav-link text-black">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="{% url 'client:client_list' %}"></use>
                                </svg>
                                Получатели рассылки
                            </a>
                        </div>
                        {% endif %}
                    </li>

                    <li>
                        {% if user.is_authenticated %}
                        <div class="container">
                            <a href="/mailing_report" class="nav-link text-black">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                    <use xlink:href="/mailing_report"></use>
                                </svg>
                                Отчет по рассылкам
                            </a>
                        </div>
                        {% endif %}
                    </li>

                    <hr>
                    <li>
                        {% if user.is_authenticated %}
                        <a class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">

                            </svg>
                            Вы вошли как:<br>
                            {{ user.first_name }}, {{ user.email }}
                            {% if  not user.is_active %}
                            <font color="red" size="4">Внимание, вы деактивированы</font>
                            {% endif %}

                            <div class="nav-link text-black">
                                <svg class="bi pe-none me-2" width="16" height="16">
                                </svg>
                                {% if user.is_superuser %}
                                <font color="red" size="4">Внимание</font>
                                <br>
                                <font color="red">Режим администратора</font>
                                {% endif %}
                            </div>
                        </a>
                        <a href="{% url 'users:logout' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:logout' %}"></use>
                            </svg>
                            Выход
                        </a>
                        <a href="{% url 'users:update' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:update' %}"></use>
                            </svg>
                            Профиль
                        </a>
                        <a href="{% url 'users:gen_pass' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:gen_pass' %}"></use>
                            </svg>
                            Сбросить пароль
                        </a>
                        {% else %}
                        <a href="{% url 'users:login' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:login' %}"></use>
                            </svg>
                            Войти
                        </a>
                        <a href="{% url 'users:password_reset' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:password_reset' %}"></use>
                            </svg>
                            Востановление пароля
                        </a>
                        <a href="{% url 'users:register' %}" class="nav-link text-black">
                            <svg class="bi pe-none me-2" width="16" height="16">
                                <use xlink:href="{% url 'users:register' %}"></use>
                            </svg>
                            Регистрация
                        </a>

                        {% endif %}
                    </li>


                </ul>
            </div>
        </div>

        {% block content %}
        {% endblock %}


    </div>
    {% include 'mailing/inc.html' %} {# подключение подшаблона #}
</div>


</body>
</html>

mailing/templates/mailing/inc.html
<h7 style="text-align: center;">2023</h7>

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-md-9">

        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            {% if user.is_authenticated %}
                <h3 class="text-center title">{{ user.first_name }} - Добро пожаловать на сайт управления рассылок</h3>

            {% else %}
                <h3 class="text-center title">Добро пожаловать на сайт управления рассылок</h3>
                <h3 class="text-center">Для использования полного функционала пожалуйста войдите в аккаунт</h3>
            {% endif %}
            <div class="row">
                <hr>
                <h3 class="text-center">Наша статистика</h3>
                <div class="table-responsive">
                    <table class="table text-center">
                        <thead>
                        <tr>
                            <th>Количество рассылок</th>
                            <th>Количество активных рассылок</th>
                            <th>количество уникальных клиентов для рассылок</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>{{ mails }}</td>
                            <td>{{ active }}</td>
                            <td>{{ clients }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                <h3 class="text-center">Статьи из блога</h3>
                <div class="row">
                    {% for article in random_article %}
                        <div class="col-md-3">
                            <div class="card-body">
                                <h5 class="card-title">Заголовок записи:<br>{{ article.title }}</h5>
                                {% if article.preview_image %}
                                    <img src="/img/{{ article.preview_image }}" class="img-fluid">
                                    <rect width="20%" height="20%"></rect>
                                {% else %}
                                    <p> нет фото</p>
                                {% endif %}
                                <p class="lead fw-normal">Краткое содержание: <br>{{ article.content|truncatechars:20 }}.</p>
                                <a class="btn btn-outline-secondary" href="{% url 'blog:detail' article.slug %}">Читать
                                    полностью</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>



{% endblock %}

mailing/templates/mailing/log_view.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-9">

    <div class="d-flex flex-column h-70 justify-content-center align-items-center">
        <h1> Отчет по рассылкам </h1>
        <h5> Справка: </h5>
        <h5> АС  - активна, FI - закончена, CR - создана </h5>
        <h5> Переодичность: DL  -день, WL  неделя, ML - месяц</h5>
        <p></p>

        {% for object in object_list %}
        {% if object.status_type == 'MANAGER' or user == object.mailing.author or object.is_superuser %}

        <div class="container text-left">
            статус рассылки (на момент создания)/время начала рассылки/периодичность:{{ object.mailing }} <br>
            дата и время последней попытки: {{ object.mailing_try }} <br>
            статус рассылки: {{ object.mailing_try_status }} <br>
            Ответ почтового сервера:{{ object.mailing_response }} <br> <hr>
        </div>

        {% endif %}
        {% endfor %}
    </div>
</div>


{% endblock %}

mailing/templates/mailing/mail_form.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="row">
            <h1> Создание рассылки </h1>
            <div class="col-md-4">
                <h1 class="text-center title">Настройки рассылки</h1>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div style="display: flex; justify-content: center; align-items: center;">
                        <button type="submit">Создать</button>
                    </div>


            </div>
            <div class="col-md-5">
                <h1 class="text-center title">Тема и текст письма</h1>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    <div class="card input">
                        <div class="col">

                            {{ form|crispy }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
     </form>
    </div>


{% endblock %}

mailing/templates/mailing/mail_form_update.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="row">
            <h1> Изменение рассылки </h1>
            <div class="col-md-4">
                <h1 class="text-center title">Настройки рассылки</h1>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}


            </div>
            <div class="col-md-5">
                <h1 class="text-center title">Тема и текст письма</h1>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    <div class="card input">
                        <div class="col">

                            {{ form|crispy }}

                        </div>
                    </div>
                {% endfor %}
                <div style="display: flex; justify-content: center; align-items: center;">
                    <button type="submit">Изменить</button>
                    <a class="btn btn-secondary blog m-2" href="{% url 'mailing:mailing_list' %}">отмена</a>
                </div>

            </div>
        </div>
        </form>
    </div>


{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">

        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1>  Удаление рассылки </h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a class="btn btn-secondary blog m-2" href="{% url 'mailing:mailing_list' %}">отмена</a>

            </form>

        </div>
    </div>


{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}


{% block content %}
<div class="col-md-9">
    <div class="d-flex flex-column h-100 justify-content-center align-items-center">
        <h1 class="text-center title">Список рассылок</h1>
        {% if user.is_authenticated %}
        <a class="btn btn-success " href="{% url 'mailing:mailing_create' %}">создать рассылку</a>
        {% endif %}
        <div class="row">
            <hr>
            {% for object in object_list %}
            {% if user.status_type == 'MANAGER' or user == object.settings.author or user.is_superuser%}
            <div class="col-md-3">
                <div class="card-body">
                    <h5 class="card-title">Тема письма:<br>{{ object.mailing_subject }}</h5>
                    <p class="card-text">Текст письма:<br>{{ object.mailing_body|truncatechars:20 }} </p>
                    {% if user == object.settings.author  or user.is_superuser%}

                    <a class="btn btn-outline-danger" href="{% url 'mailing:mailing_update' pk=object.pk %}"
                       role="button">изменить</a>


                    <a class="btn btn-outline-danger" href="{% url 'mailing:mailing_delete' pk=object.pk %}"
                       role="button">Удалить рассылку</a>
                    {% endif %}



                </div>
            </div>
            {% endif %}
            {% endfor %}
            <div class="pagination">
                {% if is_paginated %}
                {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                {% endif %}
                <span class="page-current">{{ page_obj.number }}</span>
                {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
    {% endblock %}