blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('list/', BlogListView.as_view(), name='blog_post_list'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('update/<slug:slug>/', BlogUpdateView.as_view(), name='update'),

]

client/urls.py
from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientsDetailView
from django.urls import path

app_name = ClientConfig.name
urlpatterns = [
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', ClientsDetailView.as_view(), name='client_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('client/', include('client.urls', namespace='client'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class MailingClient(models.Model):

    contact_email = models.EmailField(max_length=254, unique=True, verbose_name='контактный email')
    first_name = models.CharField(max_length=25, verbose_name='имя')
    last_name = models.CharField(max_length=25, verbose_name='фамилия')
    surname = models.CharField(max_length=25, verbose_name='отчество', **NULLABLE)
    comment = models.TextField(verbose_name='комментарии', **NULLABLE)

    def __str__(self):
        return f'Получатель {self.first_name} {self.last_name} {self.contact_email}'

    class Meta:
        verbose_name = "Клиент рассылки"
        verbose_name_plural = 'Клиенты рассылок'

client/forms.py
from django import forms
from client.models import MailingClient


class ClientForm(forms.ModelForm):
    class Meta:
        model = MailingClient
        fields = '__all__'

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.template.defaultfilters import slugify
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from client.forms import ClientForm
from client.models import MailingClient


class ClientCreateView(LoginRequiredMixin, CreateView):

    template_name = "client/create_clients.html"
    model = MailingClient
    form_class = ClientForm
    success_url = reverse_lazy('client:client_list')


class ClientListView(LoginRequiredMixin, ListView):

    model = MailingClient
    template_name = 'client/client_list.html'
    paginate_by = 6


class ClientsDetailView(LoginRequiredMixin, DetailView):

    model = MailingClient
    template_name = 'client/client_detail.html'
    context_object_name = 'item'
    pk_url_kwarg = 'pk'


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):

    model = MailingClient
    permission_required = "client.delete_mailingclient"
    login_url = 'users:login'
    redirect_field_name = 'redirect_to'
    template_name = 'client/delete_client.html'
    success_url = reverse_lazy('client:client_list')


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    model = MailingClient
    form_class = ClientForm
    permission_required = "client.change_mailingclient"
    login_url = 'users:login'
    redirect_field_name = 'redirect_to'
    template_name = 'client/update_form.html'

    def get_success_url(self) -> str:

        new_url = slugify(self.object.pk)
        return reverse('client:client_detail', args=[new_url])

client/templates/client/client_detail.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-9">

    <div class="d-flex flex-column  justify-content-center align-items-center">
        <h1> Подробнее о получателе рассылки </h1>

        <h5 class="card-title">EMAIL клиента:<br>{{ object.contact_email }}</h5>
        <p class="card-text">Имя клиента:<br>{{ object.first_name }} </p>
        <p class="card-text">Фамилия клиента:<br>{{ object.last_name }} </p>
        {% if user.status_type == 'MANAGER' or user.is_superuser%}
        <a class="btn btn-outline-danger blog m-2" href="{% url 'client:client_delete' object.pk %}">Удалить</a>
        <a class="btn btn-outline-primary blog m-2" href="{% url 'client:client_update' object.pk %}">Редактировать</a>
        {% endif %}

    </div>

    {% endblock %}

client/templates/client/client_list.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">
        <div class="d-flex flex-column  contact_email align-items-center">
            <h1> Список клиентов рассылки </h1>
            <br>
            <a class="btn btn-outline-success " href="{% url 'client:client_create' %}">Cоздать клиента</a>
            <hr>
            <div class="row">
                {% for object in object_list %}

                    <div class="col-md-6">
                        <div class="card-body">
                            <h5 class="card-title">EMAIL клиента:<br>{{ object.contact_email }}</h5>
                            <a class="detail" type="submit" href="{% url 'client:client_detail' object.pk %}"><p>
                                Подробнее...</p></a>
                        </div>
                    </div>
                {% endfor %}
                <div class="pagination">
                    {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                        {% endif %}
                        <span class="page-current">{{ page_obj.number }}</span>
                        {% if page_obj.has_next %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/create_clients.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">

        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1> Создание получателя рассылки </h1>
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div style="display: flex; justify-content: center; align-items: center;">
                <button type="submit">Создать</button>
            </div>
        </form>

        </div>
    </div>


{% endblock %}

client/templates/client/delete_client.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">

        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1>  Удаление клиента рассылки </h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a class="btn btn-secondary blog m-2" href="{% url 'client:client_list' %}">отмена</a>

            </form>

        </div>
    </div>


{% endblock %}

client/templates/client/update_form.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">

        <div class="d-flex flex-column  justify-content-center align-items-center">
            <h1> Обновление клиента рассылки </h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-danger" type="submit">Изменить</button>
                <a class="btn btn-secondary blog m-2" href="{% url 'client:client_list' %}">отмена</a>

            </form>
        </div>
    </div>


{% endblock %}