blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('list/', BlogListView.as_view(), name='blog_post_list'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('update/<slug:slug>/', BlogUpdateView.as_view(), name='update'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('client/', include('client.urls', namespace='client'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image
from django.urls import reverse
from blog.services import u_sl


NULLABLE = {'null': True, 'blank': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    slug = models.SlugField(null=False, unique=True)
    content = models.TextField(verbose_name='текст')
    preview_image = models.ImageField(upload_to='blog_images/', verbose_name='медиа', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='статус публикации')
    views_count = models.IntegerField(default=0, verbose_name='счетчик просмотров')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):


        super().save(*args, **kwargs)
        if self.preview_image:
            img = Image.open(self.preview_image.path)
            img.thumbnail((200, 200))
            img.save(self.preview_image.path)

        if not self.slug:
            self.slug = u_sl(self, self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_post_list', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

blog/forms.py
from django.utils.text import slugify
from blog.models import BlogPost
from django import forms

EXCLUTION_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево',
                   'бесплатно', 'обман', 'полиция', 'радар']

class BlogPostForm(forms.ModelForm):


    class Meta:
        model = BlogPost
        exclude = ['created_at', 'views_count', 'slug', 'user']

    def clean_title(self):
        cleaned_data = self.cleaned_data['name']
        cnt = 0
        for item in EXCLUTION_WORDS:
            if item == cleaned_data.lower():
                cnt += 1

        if cnt > 0:
            raise forms.ValidationError("слово запрещено")
        return cleaned_data

    def clean_content(self):

        cleaned_data = self.cleaned_data.get('content')
        if cleaned_data in EXCLUTION_WORDS:
            raise forms.ValidationError('слово запрещено')
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slug = slugify(instance.title)
        if commit:
            instance.save()
        return instance

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from blog.forms import BlogPostForm
from blog.models import BlogPost
from blog.utils import get_cached_for_blog_list




class BlogListView(ListView):
    """Вывод списка статей блога"""
    model = BlogPost
    template_name = 'blog/blog_post_list.html'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
         """фунция вывода + сервисная прослойка для вывода"""
         context_data = super().get_context_data()
         context_data['object'] = get_cached_for_blog_list
         return context_data



class BlogCreateView(LoginRequiredMixin, CreateView):

    model = BlogPost
    form_class = BlogPostForm
    login_url = 'users:login'
    redirect_field_name = 'redirect_to'
    template_name = 'blog/blog_post_create.html'
    success_url = reverse_lazy('blog:blog_post_list')
    def form_valid(self, form):

        form.instance.user = self.request.user
        return super().form_valid(form)



class BlogDetailView(DetailView):

    model = BlogPost
    template_name = 'blog/blog_post_detail.html'

    def get_object(self, queryset=None):

        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):

    model = BlogPost
    form_class = BlogPostForm

    template_name = 'blog/blog_post_form.html'


    def dispatch(self, request, *args, **kwargs):

        self.object = self.get_object()
        if self.object.user != self.request.user and not self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404("Вы не являетесь владельцем этого продукта.")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self) -> str:
        return reverse('blog:detail', args=[self.object.slug])


class BlogDeleteView(LoginRequiredMixin, DeleteView):

    model = BlogPost
    template_name = 'blog/blog_post_delete.html'

    success_url = reverse_lazy('blog:blog_post_list')

    def dispatch(self, request, *args, **kwargs):

        self.object = self.get_object()
        if self.object.user != self.request.user and not self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404("Вы не являетесь владельцем этого продукта.")

        return super().dispatch(request, *args, **kwargs)

blog/templates/blog/blog_post_create.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Создание записи</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit">Создать</button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_post_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Удаление записи блога {{ object.title }}</h1>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Удалить</button>
                <a class="btn btn-secondary blog m-2" href={% url 'blog:detail' object.slug %}>отмена</a>

            </form>


        </div>

    </div>



{% endblock %}

blog/templates/blog/blog_post_detail.html
{% extends 'mailing/base.html' %}
{% load static %}
{% block content %}
    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Записи в блогах</h1>
            <div class="col">
                {% if object.preview_image %}
                    <img class="entry-preview" src="{{ object.preview_image.url }}"
                         alt="...">
                {% else %}
                    <p> нет фото</p>
                {% endif %}
            </div>


            <h4 class="title">Заголовок записи <br>{{ object.title }}</h4>
            <h4 class="title mb-4">slug: {{ object.slug }}</h4>
            <h4 class="title mb-4">автор {{ object.user }}</h4>
            <h4 class="title mb-4"> текущий {{ user }}</h4>


            <div class="col">
                <p>{{ object.content }}</p>
            </div>
            <p class="mb-1">Дата создания: {{ object.created_at }}</p>
            <p class="mb-1">Количество просмотров: {{ object.views_count }}</p>
            {% if user == object.user or user.status_type == 'CONTENT_MANAGER' or user.is_superuser%}

                <a class="btn btn-outline-danger blog m-2" href={% url 'blog:delete' object.slug %}>Удалить</a>


                <a class="btn btn-outline-primary blog m-2" href={% url 'blog:update' object.slug %}>Изменить</a>
            {%endif%}

        </div>

    </div>
{% endblock %}

blog/templates/blog/blog_post_form.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Изменение записи блога {{ object.title }}</h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-danger" type="submit">Изменить</button>
                <a class="btn btn-secondary blog m-2" href={% url 'blog:detail' object.slug %}>отмена</a>

            </form>
        </div>

    </div>

{% endblock %}

blog/templates/blog/blog_post_list.html
{% extends 'mailing/base.html' %}


{% block content %}
    <div class="col-md-9">
    <div class="d-flex flex-column h-100 justify-content-center align-items-center">
        <h1 class="text-center title">Записи в блогах</h1>
        {% if user.is_authenticated %}

            <a class="btn btn-success " href="{% url 'blog:create' %}">создать запись</a>
        {% endif %}



        <div class="row">

            {% for object in object_list %}
                <div class="col-xxl-4 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="card mb-3" style="max-width: 1000px;">
                        <div class="row g-0">
                            <div class="col">
                                <img class="entry-preview{max-width: 20px; max-height: 20px;}"
                                        {% if object.preview_image %}
                                     src="{{ object.preview_image.url }}" alt="...">
                                        {% else %}
                                            <p> нет фото</p>
                                        {% endif %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">Заголовок записи:<br>{{ object.title }}</h5>
                                    <p class="card-text">Текст записи:<br>{{ object.content }} </p>
                                    <p class="card-text">Создано:{{ object.created_at }} </p>
                                    <p class="card-text">Количество просмотров:{{ object.views_count }} </p>

                                    <a class="detail" type="submit" href="{% url 'blog:detail' object.slug %}"><p>
                                        Подробнее...</p></a>


                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="pagination">
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    {% endif %}
                    <span class="page-current">{{ page_obj.number }}</span>
                    {% if page_obj.has_next %}
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}