blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogDeleteView, BlogCreateView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('list/', BlogListView.as_view(), name='blog_post_list'),
    path('detail/<slug:slug>/', BlogDetailView.as_view(), name='detail'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('create', BlogCreateView.as_view(), name='create'),
    path('update/<slug:slug>/', BlogUpdateView.as_view(), name='update'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
                  path('client/', include('client.urls', namespace='client'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, activate_account, ActivationOk, ActivationFailed, gen_pass, \
    UserForgotPasswordView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('update/', UserUpdateView.as_view(), name='update'),
    path('verify/<str:uidb64>/', activate_account, name='email_verification'),
    path('success', ActivationOk.as_view(), name='activation_ok'),
    path('failed', ActivationFailed.as_view(), name='activation_failed'),
    path("gen_pass/", gen_pass, name="gen_pass"),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# создание флага необязательного поля
NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='электронная почта')
    phone = models.CharField(max_length=50, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=20, verbose_name='страна', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    first_name = models.CharField(max_length=25, verbose_name='имя')
    last_name = models.CharField(max_length=25, verbose_name='фамилия', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='активный')

    # переопределение поля user  как основного для идентификации на емаил
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    class StatusType(models.Model):
        '''Подкласс для определения роли пользователя'''
        MANAGER = "MANAGER"
        BASE_USER = "BASE_USER"
        CONTENT_MANAGER = "CONTENT_MANAGER"
        STATUS = [
            (MANAGER, "Manager"),
            (BASE_USER, "Base_user"),
            (CONTENT_MANAGER, "Content_manager"),
        ]

    status_type = models.CharField(
        max_length=50,
        choices=StatusType.STATUS,
        default=StatusType.BASE_USER,
        verbose_name="роль")

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserUpdate(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country')

    def  __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()



class UserForgotPasswordForm(PasswordResetForm):


    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class UserSetNewPasswordForm(SetPasswordForm):


    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

users/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.generic import CreateView, UpdateView, TemplateView
from django.utils.encoding import force_str
from users.forms import UserForgotPasswordForm, UserSetNewPasswordForm
from users.forms import UserRegisterForm, UserUpdate
from users.models import User


class RegisterView(CreateView):
    """Регистрация"""
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """отправка ссылки"""
        user = form.save(commit=False)
        user.is_active = False  # User will be activated after email verification
        user.save()
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        current_site = get_current_site(self.request)
        activation_link = reverse_lazy(
            'users:email_verification', kwargs={'uidb64': uid})
        activation_url = f"{current_site}{activation_link}"
        mail_subject = 'Активируйте свой аккаунт'
        massage = render_to_string('users/email_verification.html', {
            'activation_url': activation_url
        })
        user.email_user(mail_subject, massage)

        return super().form_valid(form)


def activate_account(request, uidb64):
    """активация"""
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=int(uid))
        user.is_active = True
        user.save()
        return redirect('users:activation_ok')
    except User.DoesNotExist:
        return redirect('users:activation_failed')


class ActivationOk(TemplateView):
    """Активация успешна"""
    template_name = 'users/email_verification_done.html'


class ActivationFailed(TemplateView):
    """Активация не успешна"""
    template_name = 'users/email_verification_failed.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """Обновление юзера"""
    model = User
    form_class = UserUpdate
    template_name = "users/update_user.html"
    success_url = reverse_lazy('mailing:index')

    def get_object(self, queryset=None):
        return self.request.user


def gen_pass(request):
    """Генерация пароля https://proghunter.ru/articles/django-base-2023-password-recovery-form"""
    new_password = str(random.randint(1000, 9999))
    request.user.set_password(new_password)
    request.user.save()
    send_mail('Ваш пароль изменен',
              f"Ваш пароль: {new_password} обязательно поменяйте его", 'noreply@oscarbot.ru', [request.user.email])
    return redirect('mailing:index')


class UserForgotPasswordView(SuccessMessageMixin, PasswordResetView):
    """
    Представление по сбросу пароля по почте
    """
    form_class = UserForgotPasswordForm
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('mailing:index')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлена на ваш email'
    subject_template_name = 'users/password_subject_reset_mail.txt'
    email_template_name = 'users/password_reset_mail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Запрос на восстановление пароля'
        return context


class UserPasswordResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """
    Представление установки нового пароля
    """
    form_class = UserSetNewPasswordForm
    template_name = 'users/user_password_set_new.html'
    success_url = reverse_lazy('mailing:index')
    success_message = 'Пароль успешно изменен. Можете авторизоваться на сайте.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Установить новый пароль'
        return context

users/templates/users/email_verification.html
{{ user.username }}!

Пожалуйста, перейдите по ссылке ниже для активации вашей учетной записи:

http://{{ activation_url}}

Если это делаете не вы, то просто проигнорируйте это письмо.

users/templates/users/email_verification_done.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-9">
    {% csrf_token %}
    <h1>Активация прошла успешно</h1>
    <p>Ваш аккаунт успешно создан. Теперь вы можете войти на сайт.</p>
</div>
{% endblock %}

users/templates/users/email_verificatione_failed.html
{% extends 'mailing/base.html' %}


{% block content %}

    <h1>ERROR</h1>
    <p>Проверьте ссылку для активации или обратитесь к
        администратору.</p>
{% endblock %}

users/templates/users/generate_new_pass.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Востановление пароля</h1>
            <<form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card">
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
                <a class="btn btn-primary" href="{% url 'users:gen_pass' %}">Отправить новый пароль на почту</a>
            </div>
        </form>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Вход в профиль</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <div style="display: flex; justify-content: center; align-items: center;">
                    <button class="btn btn-success" type="submit">Войти</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/pass_reset_unlog.html
{% extends 'mailing/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-9">
    <h2>Восстановление пароля</h2>
    <form method="post" action="{% url 'users:gen_pass_unlog' email='' %}">
        {% csrf_token %}
        <label for="email">E-mail:</label>
        <input type="email" name="email" id="email" required>
        <input type="submit" value="Сбросить пароль">
    </form>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'mailing/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">

        <h2>Восстановление пароля</h2>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Отправить</button>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_mail.html
{% autoescape off %}

    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и выберите новый пароль:
	{% block reset_link %}
	    {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	Ваше имя пользователя, если вы забыли: {{ user.get_username }}

	Спасибо за использование нашего сайта!

	The {{ site_name }} team

{% endautoescape %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">регистрация</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <div style="display: flex; justify-content: center; align-items: center;">
                    <button class="btn btn-success" type="submit">Регистрация</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/update_user.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
        <div class="d-flex flex-column h-100 justify-content-center align-items-center">
            <h1 class="text-center title">Изменение учетных данных</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}

                <div style="display: flex; justify-content: center; align-items: center;">
                    <button class="btn btn-success" type="submit">Подтверждение</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-md-9">
    <div class="d-flex flex-column h-100 justify-content-center align-items-center">
        <h1 class="text-center title">Запрос на востановление пароля</h1>
        <h4 class="text-center title">Ведите адрес почты указаный при регистрации</h4>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-dark mt-2">Отправить запрос на востановление пароля</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/user_password_set_new.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="col-md-9">
<div class="card-title nth-card-title">
                <h4>Установить новый пароль</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Подтвердить</button>
            </form>
    </div>
{% endblock %}